title: Ubald.dev
tagline: I need to rant about code
description: >- # this means to ignore newlines
    Hi, my name is Ubald and this is me ranting about code.
baseurl: ""
url: "https://ubald.dev"
email: ubald@ubald.dev
twitter_username: ubaldev
github_username: ubald

permalink: /:categories/:slug

markdown: kramdown
highlighter: rouge

kramdown:
    input: GFM
    syntax_highlighter: rouge

    syntax_highlighter_opts:
        css_class: "highlight"
        # line_numbers: true # bad idea, spans don't need linenos and would inherit this option
        span:
            line_numbers: false
        block:
            line_numbers: true
            start_line: 1

plugins:
    - jemoji
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-seo-tag
    - jekyll-paginate

paginate: 2
paginate_path: "/posts/:num/"

collections:
    authors:
        output: true

defaults:
    # - scope:
    #       path: ""
    #   values:
    - scope:
          path: ""
          type: posts
      values:
          layout: post
          type: post
          author: ubald
    - scope:
          path: ""
          type: pages

      values:
          layout: page
          type: page
    - scope:
          path: ""
          type: authors
      values:
          permalink: "/authors/:title"
          layout: author
          type: author
