name: Publish Jekyll Site

on:
    push:
        branches:
            - master
            - test-actions

jobs:
    build:
        name: Build Jekyll Site
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-ruby@v1
              with:
                  ruby-version: "2.7"

            - uses: actions/checkout@v2

            - uses: actions/cache@v2
              with:
                  path: vendor/bundle
                  key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-gems-

            - name: Bundle install
              run: |
                  bundle config path vendor/bundle
                  bundle install --jobs 4 --retry 3

            - name: Build site
              env:
                  JEKYLL_ENV: production
              run: bundle exec jekyll build

            - name: Publish site
              run: |
                  cd _site
                  git init
                  git remote add origin "https://${{ github.token }}@github.com/${{ github.repository }}.git"
                  git fetch --prune
                  git checkout pub
                  git config user.email "ubald@ubaldesign.com"
                  git config user.name "Jekyll Build"
                  git config push.default current
                  git commit -m "Sync build changes"
                  git push origin
