name: Publish Hugo Site

on:
    push:
        branches:
            - master
            - test-actions

jobs:
    build:
        name: Build Hugo Site
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Hugo install
              run: |
                  wget https://github.com/gohugoio/hugo/releases/download/v0.76.3/hugo_extended_0.76.3_Linux-64bit.tar.gz
                  tar xf hugo_extended_0.76.3_Linux-64bit

            - name: Build site
              run: ./hugo --environment production --minify

            - name: Publish site
              run: |
                  mkdir pub
                  cd pub
                  git init
                  git remote add origin "https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git"
                  git fetch --prune
                  git checkout -b pub origin/pub
                  git rm -r --ignore-unmatch '*'
                  cp -r ../public/. .
                  cp ../CNAME .
                  git add --all
                  git config user.email "ubald@ubaldesign.com"
                  git config user.name "Hugo Build"
                  git config push.default current
                  git commit -m "Sync build changes"
                  git push origin
